# _config.yml
title: The Pet Eye Guide
description: Everything you need to know about pet eye care
author:
  name: Dr Francisco M. GÃ³mez V. 
url: "https://thepeteyeguide.com" 
theme: minima

# Add navigation links
minima:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "Products"
      url: "/products.html"
    - title: "Photo"
      url: "/photo/"

# setting colours
minima:
skin: null
  
